In [1]:
with open('wap.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
len(text)

3227578

In [3]:
chars = sorted(list(set(text)))


In [4]:
len(chars), chars

(112,
 ['\n',
  ' ',
  '!',
  '#',
  '$',
  '%',
  '(',
  ')',
  '*',
  ',',
  '-',
  '.',
  '/',
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  ':',
  ';',
  '=',
  '?',
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
  '[',
  ']',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
  'À',
  'Á',
  'É',
  'à',
  'á',
  'â',
  'ä',
  'æ',
  'ç',
  'è',
  'é',
  'ê',
  'ë',
  'í',
  'î',
  'ï',
  'ó',
  'ô',
  'ö',
  'ú',
  'ü',
  'ý',
  'œ',
  '—',
  '‘',
  '’',
  '“',
  '”',
  '•',
  '™',
  '\ufeff'])

In [5]:
c_to_i = {c: i for i, c in enumerate(chars)}
i_to_c = {i: c for i, c in enumerate(chars)}

encode = lambda x: [c_to_i[c] for c in x]
decode = lambda x: ''.join([i_to_c[i] for i in x])

In [6]:
encode('hello'), decode([72, 69, 76, 76, 79])

([62, 59, 66, 66, 69], 'rovvy')

In [7]:
decode([62, 59, 66, 66, 69])

'hello'

In [8]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([3227578]) torch.int64
tensor([111,  46,  62,  59,   1,  42,  72,  69,  64,  59,  57,  74,   1,  33,
         75,  74,  59,  68,  56,  59,  72,  61,   1,  59,  28,  69,  69,  65,
          1,  69,  60,   1,  49,  55,  72,   1,  55,  68,  58,   1,  42,  59,
         55,  57,  59,   0,   1,   1,   1,   1,   0,  46,  62,  63,  73,   1,
         59,  56,  69,  69,  65,   1,  63,  73,   1,  60,  69,  72,   1,  74,
         62,  59,   1,  75,  73,  59,   1,  69,  60,   1,  55,  68,  79,  69,
         68,  59,   1,  55,  68,  79,  77,  62,  59,  72,  59,   1,  63,  68,
          1,  74])


In [10]:
text[:100]

'\ufeffThe Project Gutenberg eBook of War and Peace\n    \nThis ebook is for the use of anyone anywhere in t'

In [12]:
n = int(0.9*len(data))
train_data, val_data = data[:n], data[n:]

In [13]:
block_size = 8

In [18]:
torch.manual_seed(42)
batch_size = 4
block_size = 8

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    if split == 'train':
        data = train_data
    else:
        data = val_data
    ix = torch.randint(data.size(0) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print("inputs:")
print(xb.shape)
print(xb)
print("targets")
print(yb.shape)
print(yb)



inputs:
torch.Size([4, 8])
tensor([[ 1, 77, 62, 55, 74,  1, 77, 59],
        [58, 59,  1, 74, 62, 55, 74,  1],
        [66, 66,  1, 56, 59, 63, 68, 61],
        [ 1, 55, 58, 64, 75, 74, 55, 68]])
targets
torch.Size([4, 8])
tensor([[77, 62, 55, 74,  1, 77, 59,  1],
        [59,  1, 74, 62, 55, 74,  1, 59],
        [66,  1, 56, 59, 63, 68, 61,  0],
        [55, 58, 64, 75, 74, 55, 68, 74]])
